name: buildAndDeploy
on:
  pull_request: 
    branches:
      - master
    types: closed
jobs:
  buildBinFile:
    runs-on: ubuntu-20.04
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          - name: go-crossbuild
      - name: build
        run: |
          go build -v -o bot
      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: 'rinat'
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "bot"
          target: "bot"
      - name: deploy
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: 185.251.91.103
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            ./bot
            
            
  
