

name: tag


on:
  pull_request:
    branches:
      - master
    types: closed
    
jobs:
  tagCreate:
    runs-on: ubuntu-20.04
    outputs:
      tagOutput: ${{ steps.tagver.outputs.tag }}
    steps:
      - name: Tag
        id: tagver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
